version: '3'
services:
  seleniumChrome:
    image: minium/selenium-grid-extras-chrome:2.0.1
    build: .
    container_name: selenium-grid-extras-chrome
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "5555:5555"
      - "3100:3000"
      - "4444:4444"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - SE_OPTS="-debug true"
    volumes:
       - /dev/shm:/dev/shm 
       - ./selenium_grid_extras_config_solo.json:/opt/selenium/selenium_grid_extras_config.json
       - ./node_solo.json:/opt/selenium/node_5555.json
       - ./log4j.properties:/opt/selenium/log4j.properties
       - ../Hub/entry_point.sh:/opt/bin/entry_point.sh